name: Bug report
description: Report a defect in pgp-tools
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Command: `pgp-list-recipients ...`
        2. Output: ...
    validations:
      required: true

  - type: input
    id: pgp_tools_version
    attributes:
      label: pgp-tools version
      description: pip show pgp-tools
    validations:
      required: true

  - type: input
    id: gpg_version
    attributes:
      label: GnuPG version
      description: gpg --version
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
